version: '3'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: crown79
      MYSQL_DATABASE: mocksocialmediadb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: bright79
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - app-network
  backend:
    restart: always
    image: 353386523821.dkr.ecr.eu-west-2.amazonaws.com/public-tech/ofcom-user-controls-application-backend:latest
    ports:
      - "8081:8081"
    environment:
      - MYSQL_HOST=db
      - NODE_ENV=production
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
  frontend:
    restart: always
    image: 353386523821.dkr.ecr.eu-west-2.amazonaws.com/public-tech/ofcom-user-controls-application-frontend:latest
    environment:
      - MYSQL_HOST=db
      - NODE_ENV=production
      - PORT=8080
    ports:
      - "8080:8080"
    links:
      - "backend:local"
    depends_on:
      - backend
    networks:
      - app-network
networks:
  app-network:
    driver: bridge